title: Bram reads books
tagline: I read books, and sometimes I like writing about them too, when inspiration strikes.
description: I read books, and sometimes I like writing about them too, when inspiration strikes.
author: Bram Vandenbussche
image_url: /assets/img/book_icon.png

# Socials
twitter-handle: vandenbusschebr
instagram-handle: bram.plays.games
linkedin-handle: bramvandenbussche

# Base URL
baseurl: ""
url: "https://books.bramvandenbussche.be"
google_analytics: UA-5000335-12

# Build settings
date_format: "%b %-d, %Y"
excerpt_separator: <!--more-->
star-rating-icon: fa-solid fa-star
permalink: /:slugified_categories/:year/:month/:day/:slug:output_ext

# Compress
compress_html:
  clippings: all

# Exclude files from build
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins: 
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-responsive-image

highlighter: rouge

# Default Markdown Engine
markdown: kramdown

# Sitewide default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "review"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "series"
    values:
      layout: "collection_series"
  -
    scope:
      path: ""
      type: "authors"
    values:
      layout: "collection_authors"

# Define custom collections
collections:
  series:
    output: true
  authors:
    output: true

# Relative links configuration
# See: https://github.com/benbalter/jekyll-relative-links
relative_links:
  enabled:     true
  collections: true

# Responsive image configuration
# See: https://github.com/wildlyinaccurate/jekyll-responsive-image
responsive_image:
  template: _includes/responsive-image.html
  sizes:
    - width: 83
    - width: 170
    - width: 200
    - width: 250
    - width: 270
    - width: 340

# Feed configuration
# See: https://github.com/jekyll/jekyll-feed
feed:
  excerpt_only: true
  posts_limit: 20

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
# https://github.com/sverrirs/jekyll-paginate-v2
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: true

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 12

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: ''

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  indexpage: 'index'

############################################################


############################################################
# Site configuration for the Auto-Pages feature
# The values here represent the defaults if nothing is set
autopages:

  # Site-wide kill switch, disable here and it doesn't run at all 
  enabled: true

  # Category pages, omit entire config element to disable
  categories: 
    # Optional, the list of layouts that should be processed for every category found in the site
    layouts: 
      - 'autopage_category.html'
    # Optional, the title that each category paginate page should get (:cat is replaced by the Category name)
    title: 'Posts in category :cat'
    # Optional, the permalink for the  pagination page (:cat is replaced), 
    # the pagination permalink path is then appended to this permalink structure
    permalink: '/category/:cat'
    # Optional, when true logging related to category pages will be supressed.
    silent: false
    slugify:
      mode: 'default'   # :cat is slugified. Modes: default, raw, pretty, ascii, latin
      case: false       # Whether to replace all uppercase letters with their lowercase counterparts

  # Collection pages, omit to disable
  collections:
    layouts: 
      - 'autopage_collection.html'
      # - 'autopage_collection_series.html'
      # - 'autopage_collection_tags.html'
    title: 'Posts in collection :coll' # :coll is replaced by the collection name
    permalink: '/collection/:coll'
    silent: false
    slugify:
      mode: 'default'   # :coll is slugified.
      case: false 
  
  # Tag pages, omit to disable
  tags:
    layouts: 
      - 'autopage_tags.html'
    title: 'Posts tagged with :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'
    silent: false
    slugify:
      mode: 'default'   # :tag is slugified.
      case: false