# TITLE OF YOUR SITE
title: Bram reads books
tagline: I read books, and sometimes I like writing about them too, when inspiration strikes.
image_url: assets/img/book_icon.png

# Socials
twitter-handle: vandenbusschebr
instagram-handle: bram.plays.games
linkedin-handle: bramvandenbussche

# Base URL
baseurl: ""
url: "/"
google_analytics: UA-5000335-12

# Build settings
paginate: 5
paginate_path: "/page:num"
date_format: "%b %-d, %Y"
excerpt_separator: <!--more-->

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

plugins:
  - jekyll-paginate

highlighter: rouge

# Default Markdown Engine
markdown: kramdown
