# TITLE OF YOUR SITE
title: Bram reads books
image_url: assets/img/book_icon.png

google_analytics: UA-5000335-12


# Base URL
baseurl: ""
theme: 

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

plugins:
  - jekyll-paginate_path
  - jekyll-postcss

 # Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge

# Default Markdown Engine
markdown: kramdown
