version: '3'

services:
  generator:
    build: .
    container_name: books-generator
    # image: jekyll/jekyll:4.0
    environment:
      - JEKYLL_VERSION=4.0
      - JEKYLL_ENV=development
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle:cached
    command: jekyll serve --watch --incremental --config _config.yml --host 0.0.0.0 --livereload --force_polling
    ports:
      - "4001:4000"