name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        
    # - name: ftp-action
    #   # You may pin to the exact commit or the version.
    #   # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
    #   uses: sebastianpopp/ftp-action@v2.0.0
    #   with:
    #     # FTP host
    #     host: srv008.web.ichtushosting.com
    #     # FTP user
    #     user: ${{ secrets.FTP_USR }}
    #     # FTP password
    #     password: ${{ secrets.FTP_PWD }}
    #     # Force SSL encryption
    #     forceSsl: true # optional, default is false
    #     # Local directory
    #     localDir: _site/ # optional, default is .
    #     # Remote directory
    #     remoteDir: web/ # optional, default is .
    
    - name: FTP Deployer
      # You may pin to the exact commit or the version.
      # uses: sand4rt/ftp-deployer@b4d8a88f104b46a1bcfac8f69b3413986cc0ce28
      uses: sand4rt/ftp-deployer@v1.3
      with:
        # SFTP on
        sftp: true # optional
        # FTP host URL like: ftp.host.com or sftp.host.com
        host: ${{ secrets.FTP_HOST }}
        # FTP port
        # port: # optional, default is 21
        # Ftp username
        username: ${{ secrets.FTP_USR }}
        # Ftp password
        password: ${{ secrets.FTP_PWD }}
        # The remote folder location of your FTP server
        remote_folder: web/_site/ # optional
        # The local folder location
        local_folder: _site/ # optional, default is dist
        # Remove existing files inside FTP remote folder
        cleanup: true # optional
        # includes
        # include: [] # optional
        # exclude: []  # optional
        # passive
        pasive: true # optional
