name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
        
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: srv008.web.ichtushosting.com
        # FTP user
        user: $(FTP_USR)
        # FTP password
        password: $(FTP_PWD)
        # Force SSL encryption
        forceSsl: true # optional, default is false
        # Local directory
        localDir: _site/ # optional, default is .
        # Remote directory
        remoteDir: web/_site # optional, default is .
      
